from building import *

cwd = GetCurrentDir()
src = []

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_UART'):
    src += ['drv_usart.c']

group = DefineGroup('PY32_Drivers', src, depend=['SOC_FAMILY_PY32'], CPPPATH=[cwd])

Return('group')
