import os
from building import *

cwd = GetCurrentDir()
objs = []
for name in ['applications', 'board', 'packages']:
    script = os.path.join(cwd, name, 'SConscript')
    if os.path.isfile(script):
        objs += SConscript(os.path.join(name, 'SConscript'))

Return('objs')
